# Generated by Django 3.1 on 2020-08-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200808_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_phone',
            field=models.CharField(max_length=11),
        ),
    ]
